apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-deployment
spec:
  selector:
    matchLabels:
      app:  book-service-k8
  replicas: 3
  template:
    metadata:
      labels:
        app:  book-service-k8
    spec:
      containers:
        - name: book-service
          image: book-service:1.0
          ports:
            - containerPort: 8082
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: book-service-svc
spec:
  selector:
    app: book-service-k8
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 8082
  type: ClusterIP