apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  selector:
    matchLabels:
      app:  gateway-service-k8
  replicas: 1
  template:
    metadata:
      labels:
        app:  gateway-service-k8
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service-svc
spec:
  selector:
    app: gateway-service-k8
  ports:
    - protocol: "TCP"
      port: 8083
      targetPort: 8083
  type: NodePort
