INSERT INTO BOOK_DATA(ISBN,TITLE,PUBLISHED_DATE,TOTAL_COPIES,ISSUED_COPIES,AUTHOR) VALUES ('ISBN0001','RAMAYANA',to_date('2020-02-02','YYYY-MM-DD'),15,10,'VALMIKI');
INSERT INTO BOOK_DATA(ISBN,TITLE,PUBLISHED_DATE,TOTAL_COPIES,ISSUED_COPIES,AUTHOR) VALUES ('ISBN0002','MAHABHARAT',to_date('2019-02-02','YYYY-MM-DD'),20,10,'VED VYAS');
INSERT INTO BOOK_DATA(ISBN,TITLE,PUBLISHED_DATE,TOTAL_COPIES,ISSUED_COPIES,AUTHOR) VALUES ('ISBN0003','HARRY POTTER',to_date('2018-02-02','YYYY-MM-DD'),25,10,'J.K.ROWLING');
INSERT INTO BOOK_DATA(ISBN,TITLE,PUBLISHED_DATE,TOTAL_COPIES,ISSUED_COPIES,AUTHOR) VALUES ('ISBN0004','GAME OF THRONES',to_date('2017-02-02','YYYY-MM-DD'),25,10,'GEROGE MARTIN');
INSERT INTO BOOK_DATA(ISBN,TITLE,PUBLISHED_DATE,TOTAL_COPIES,ISSUED_COPIES,AUTHOR) VALUES ('ISBN0005','TINTIN',to_date('2017-02-02','YYYY-MM-DD'),25,10,'TINTIN');
INSERT INTO BOOK_DATA(ISBN,TITLE,PUBLISHED_DATE,TOTAL_COPIES,ISSUED_COPIES,AUTHOR) VALUES ('ISBN0006','ORACLE JAVA',to_date('2017-02-02','YYYY-MM-DD'),25,10,'MCGRAW');
INSERT INTO BOOK_DATA(ISBN,TITLE,PUBLISHED_DATE,TOTAL_COPIES,ISSUED_COPIES,AUTHOR) VALUES ('ISBN0007','TALE OF SHIVA',to_date('2021-02-02','YYYY-MM-DD'),25,10,'D.PATTNAIK');
INSERT INTO BOOK_DATA(ISBN,TITLE,PUBLISHED_DATE,TOTAL_COPIES,ISSUED_COPIES,AUTHOR) VALUES ('ISBN0008','TALE OF VISHNU',to_date('2022-02-02','YYYY-MM-DD'),25,10,'D.PATTNAIK');