INSERT INTO ISSUE_DATA(ISBN,CUST_ID,CUST_NAME,NO_OF_COPIES) VALUES ('ISBN0001','CU001','VENKAT',2);
INSERT INTO ISSUE_DATA(ISBN,CUST_ID,CUST_NAME,NO_OF_COPIES) VALUES ('ISBN0002','CU002','DHEERAJ',3);
INSERT INTO ISSUE_DATA(ISBN,CUST_ID,CUST_NAME,NO_OF_COPIES) VALUES ('ISBN0003','CU003','MAYANK',2);